Deployment:
  app_name: chatapp
  db_name: postgres 
  app_replicas: 2
  db_replicas: 1
  db_key_name: db-keys
  db_claim: postgres-claim
  db_volume: postgres-volume
  app_image_url: 416604440517.dkr.ecr.ap-south-1.amazonaws.com/chatapp:latest
  db_image: postgres:latest
  app_port: 8000


Service:
  app_port: 8000
  app_name: chatapp
  db_name: postgres
  app_svc_name: chatapp-lb
  db_svc_type: ClusterIP
  app_svc_type: ClusterIP
  app_svc_port: 80
  db_svc_port: 5432


#app_name: chatapp
#app_replicas: 2
#app_image_url: 416604440517.dkr.ecr.ap-south-1.amazonaws.com/chatapp:latest
#app_port: 8000
#db_name: postgres
#db_replicas: 1
#db_image: postgres:latest
#db_key_name: db-keys
#db_volume: postgres-volume
#db_claim: postgres-claim
#app_svc_name: chatapp-lb
#db_port: 5432
#db_svc_type: ClusterIP
#app_svc_port: 80
#app_svc_type: ClusterIP
